language: php
php:
  - '7.0'
  - '7.1'
  - '7.2'
env:
  - LARAVEL_VERSION='5.5'
  - LARAVEL_VERSION='5.6'
install:
  composer install --no-interaction
  composer require illuminate/http:${LARAVEL_VERSION} illuminate/support:${LARAVEL_VERSION}
